services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost

  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SS_CLIENT_ID=${SS_CLIENT_ID}
      - SS_CLIENT_SECRET=${SS_CLIENT_SECRET}
      - SS_STORE_ID=${SS_STORE_ID}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - ./backend:/app



      # Ensure backend code changes are reflected without rebuilding container
      # Mount backend source code into container for development
      # Database credentials passed from environment variables
