services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=https://gymmolly.bodytools.work
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/data/gymmolly.db
      - SS_CLIENT_ID=${SS_CLIENT_ID}
      - SS_CLIENT_SECRET=${SS_CLIENT_SECRET}
      - SS_STORE_ID=${SS_STORE_ID}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      # Mount data directory for SQLite database persistence
      - ./data:/app/data
      # Mount uploads directory for file attachments
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/inventory"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped